apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: visus
spec:
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        # - effect: NoSchedule
        #  key: node-role.kubernetes.io/master
      containers:
        - image: cockroachdb/visus:v1.0.0
          name: visus
          command: ["/usr/bin/visus",
                    "start",
                    "--bind-cert", "/cockroach/cockroach-cert/client.root.crt", 
                    "--bind-key", "/cockroach/cockroach-cert/client.root.key", 
                    "--ca-cert", "/cockroach/cockroach-cert/ca.crt", 
                    "--url","postgresql://root@localhost:26257/defaultdb",
                    "--bind-addr",":8888"]
          # args: ["--insecure", "--url postgresql://root@host.docker.internal:26257/defaultdb"]
          ports:
          - containerPort: 8888
            name: http
            hostPort: 8889
          volumeMounts:
          - name: certs
            mountPath: /cockroach/cockroach-cert
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        projected:
          defaultMode: 288
          sources:
          - secret:
              items:
              - key: tls.crt
                path: node.crt
              - key: tls.key
                path: node.key
              name: cockroachdb-node-secret
          - secret:
              items:
              - key: tls.crt
                path: client.root.crt
              - key: tls.key
                path: client.root.key
              - key: tls.crt
                path: client.node.crt
              - key: tls.key
                path: client.node.key
              - key: tls.crt
                path: ui.crt
              - key: tls.key
                path: ui.key
              name: cockroachdb-client-secret
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: cockroachdb-ca-secret-crt
